### ISSUE TITLE
laravel :client cannot be authenticated: status 419

### ISSUE THREAD

**Issue by nowfalsalahudeen** [MrBin99/LaravelEchoAndroid#4]
laravel :client cannot be authenticated: status 419
this occurs when android client connected to laravel server (using private channel and successful.y connected with public channel)

i searched a lot and got an answer. he said client need to pass csrf token .how can i do that

**Comment by MrBin99** [comment]
Hi,
It's very weird because when you're developing an API you don't need an CSRF token because it's a token generated by the server for a web client such as a browser.

Please check the function on your Laravel app to authenticate the user (routes/channel.php), and please check you are providing a good Bearer token in headers of Echo (on Android - https://github.com/MrBin99/LaravelEchoAndroid#creation).

**Comment by nowfalsalahudeen** [comment]
Please check the function on your Laravel app to authenticate the user (routes/channel.php), and please check you are providing a good Bearer token in headers of Echo 

i didnt get you. where can i configured..basically am an android dev.

Broadcast::channel('channel1', function ()
{
    return true;
    return [
        'id' => Auth::user()->id,
        'name' => Auth::user()->first_name.' '.Auth::user()->last_name
    ];
});

i want to listen this private channel1 . this one used in wed .so i want use this android too

**Comment by nowfalsalahudeen** [comment]
{
  "authHost": "http://127.0.0.1:8000",
  "authEndpoint": "/broadcasting/auth",
  "clients": [
    {
      "appId": "7728e21aadd55ghghghca5",
      "key": "f13536ff62dsfe56dsfdsf093549ae68404fds214592"
    }
  ],
  "database": "redis",
  "databaseConfig": {
    "redis": {},
    "sqlite": {
      "databasePath": "/database/laravel-echo-server.sqlite"
    }
  },
  "devMode": false,
  "host": null,
  "port": "8443",
  "protocol": "http",
  "socketio": {},
  "sslCertPath": "",
  "sslKeyPath": "",
  "sslCertChainPath": "",
  "sslPassphrase": "",
  "apiOriginAllow": {
    "allowCors": true,
    "allowOrigin": "http://192.168.1.99",
    "allowMethods":"GET, POST",
    "allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
  }
}

this is the echo server configuration json..

**Comment by MrBin99** [comment]
Ok, so how (on your Android app) you log the user in ? I think you must have some routes in your application which need a authenticated user ?

So in this routes you must pass something, somehow to log the user in because you are consuming an API and you don't/can't have sessions on API.

Maybe, you are passing a header 'Authorization: Bearer <token>' for your HTTP calls which need a authentication.

So with this, the Laravel app can check if the user logged in a retreive it for you to use in your application. That's for methods in your controllers.

**Comment by MrBin99** [comment]
For WebSocket it's different.

For presence and private channels, Laravel Echo Server will contact your Laravel app to see if the user can access this channel, it use for that the name of the channel and the token you sent here https://github.com/MrBin99/LaravelEchoAndroid#basic-usage on Android.

If there's no token, the Laravel app can't authenticate the user so, the user can't access the channel.

If there is a token, Laravel will check if the user can access the channel by calling the corresponding channel function in channels.php.

If this function return false, it means that the user cannot access the channel otherwise, this function must return an array containing all data you want to broadcast to all the user in this channel for saying that a new user entering this channel (you can use that to help you build this function https://laravel.com/docs/5.6/broadcasting#presence-channels).

I think your problem is that Laravel does not receive a valid token to authenticate the user.
But don't mismatch, for Websocket, your Android app must connect to the Laravel Echo Server, and this Laravel Echo Server contact your Laravel PHP server.

Please tell me if I make myself clear ? If you need more explanation, or if you have more questions don't hesitate to ask.

**Comment by nowfalsalahudeen** [comment]
Thanks ..in android app it worked.(changed some config in laravel middleware). but now it not working through browsers(Broadcast::routes). enabling private channel auth for api(android) breaks socket listening in browser .how it can be working on both browser and android client

**Comment by MrBin99** [comment]
What did you changed in your middleware ?

**Comment by nicolasvahidzein** [comment]
I would have loved to know, i am stuck with the exact same thing on vuejs.
